### ISSUE TITLE
Error running sigma rules

### ISSUE THREAD

**Issue by s4lva2** [ppll0p1s/SigmaShooter#3] opened 2020-08-05 08:44 UTC
Clean installation. When I try to run the example rule i get the following error in logs:

Executed: runAllRules
[●] 2020/08/05 10:40:40.658624 http2: panic serving 192.168.1.145:48356: interface conversion: interface {} is nil, not float64
goroutine 60 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc0001eb520, 0xc0000d1f8e, 0xc000100900)
	/usr/local/go/src/net/http/h2_bundle.go:5713 +0x16b
panic(0x844140, 0xc00024fb90)
	/usr/local/go/src/runtime/panic.go:969 +0x166
SigmaShooter/web.runAllRules(0x960140, 0xc0001eb520, 0xc00029a200)
	/home/xxx/go/src/SigmaShooter/web/apiController.go:488 +0x1913
net/http.HandlerFunc.ServeHTTP(0x8d8480, 0x960140, 0xc0001eb520, 0xc00029a200)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000e8000, 0x960140, 0xc0001eb520, 0xc00029a000)
	/home/xxx/go/src/github.com/gorilla/mux/mux.go:210 +0xe2
SigmaShooter/web.headerMiddleware.func1(0x960140, 0xc0001eb520, 0xc00029a000)
	/home/xxx/go/src/SigmaShooter/web/router.go:26 +0x658
net/http.HandlerFunc.ServeHTTP(0xc00000f500, 0x960140, 0xc0001eb520, 0xc00029a000)
	/usr/local/go/src/net/http/server.go:2041 +0x44
net/http.(*ServeMux).ServeHTTP(0xc4ba40, 0x960140, 0xc0001eb520, 0xc00029a000)
	/usr/local/go/src/net/http/server.go:2416 +0x1a5
net/http.serverHandler.ServeHTTP(0xc00011a000, 0x960140, 0xc0001eb520, 0xc00029a000)
	/usr/local/go/src/net/http/server.go:2836 +0xa3
net/http.initALPNRequest.ServeHTTP(0x961200, 0xc0000fd710, 0xc0000b5180, 0xc00011a000, 0x960140, 0xc0001eb520, 0xc00029a000)
	/usr/local/go/src/net/http/server.go:3410 +0x8d
net/http.(*http2serverConn).runHandler(0xc000100900, 0xc0001eb520, 0xc00029a000, 0xc00026a6a0)
	/usr/local/go/src/net/http/h2_bundle.go:5720 +0x8b
created by net/http.(*http2serverConn).processHeaders
	/usr/local/go/src/net/http/h2_bundle.go:5454 +0x4e1

**Comment by ppll0p1s** [comment] 2020-08-05 16:37
Hi s4lva2! Thanks for reporting this issue.

It seems that the problem is related with the new version of Sigma, 0,17,0, 
When I released Sigmashooter App I had tested it using Sigma, version 0,16.0.

Look this Sigma conversion comparing both Sigma versions:
Sigma 0.16.0:
\# sigmac -t graylog rules/powershell_from_winword.yml 
(EventID:"1" AND Image:("*powershell.exe*") AND ParentImage:("*WINWORD.EXE*"))

Sigma 0.17.0:
\# sigmac -t graylog rules/powershell_from_winword.yml
(EventID:"1" AND Image.keyword:(*powershell.exe*) AND ParentImage.keyword:(*WINWORD.EXE*))

Sigma 0.17.0 is deleting the quotes!

So, when the encoded url is sent to Graylog, it shows this error:
Encoded URL:
<graylog>/api/search/universal/relative?decorate=true&query=%28EventID%3A%221%22+AND+Image.keyword%3A%28%2Apowershell.exe%2A%29+AND+ParentImage.keyword%3A%28%2AWINWORD.EXE%2A%29%29+AND+NOT+agentName%3ASigmaShooterAgent&range=86400

Graylog HTTP erro:
{"type":"DetailedError","message":"**Unable to perform search query\n\nFailed to parse query** [(EventID:\"1\" AND Image.keyword:(*powershell.exe*) AND ParentImage.keyword:(*WINWORD.EXE*)) AND NOT agentName:SigmaShooterAgent]","details":["Failed to parse query [(EventID:\"1\" AND Image.keyword:(*powershell.exe*) AND ParentImage.keyword:(*WINWORD.EXE*)) AND NOT agentName:SigmaShooterAgent]"]}

Graylog can't parse this query..

Let me make some test with this version of Sigma and i will close the issue.

For the moment, you can run other Sigma rule (or just delete * sign) ;)

**Comment by s4lva2** [comment] 2020-08-06 07:22
Hello ppll0p1s,

First thing, I want to thank your quick response

I checked the command you said (sigmac -t graylog rules/powershell_from_winword.yml) and the result I got was the same as you show in the first example, so I think the version I have is the 0.16.0, so maybe the problem  is not the same

I have to say that I installed sigma using pip3 installing the package sigmatools version 0.9, in case it helps you

**Comment by ppll0p1s** [comment] 2020-08-06 07:31
Hi s4lva2,

mm.. as i said.. i have to make some more tests with Sigma to try to solve this... :S 

For the moment, you can uncomment the line 664 in the file web/helpers.go , this will print you the encoded url sent to graylog.
Then, you can copy and paste in the web navigator and observe what error shows Graylog... 

Yo can copy this to this issue and maybe i can help you!

Thanks s4lva2, and srry for the error..

**Comment by s4lva2** [comment] 2020-08-06 09:03
Hello again,

I uncommented the line 664 (after that, I recompiled the app) but I dont get any url in log file  when I try to run the rules from the sigmashooter web interface. I added some new prints inside the function runRuleQueryToGraylog but none is executed, so I think this function is not reached. 
Is logfile the place where I have to check for the encoded url?
(Im noob  so maybe Im doing the things you tell me wrong...)

I followed a manual to install graylog + sigmashooter and it says that I have to config an input in graylog using 12201 UDP port. Then in sigmashooter.conf , I have to config the parameter siemPortInput to 12202
If I look open ports in my graylog server, I only have  port 12201 opened
Could it be this part of the error?

**Comment by ppll0p1s** [comment] 2020-08-07 12:23
Hi S4lva2,

The output of the line 664 will be printed in the terminal where you run the app, if you want to log this, you can change fmt library to log.

On the other hand, the var siemPortInput will be used to send alerts to graylog in case sigma rules find results in the SIEM events.

First, try to obtains the encoded url you are sending to GRaylog and copy to the web navigator and observe the result, maybe the error is there.
If not, you can run a tcpdump to analyse the traffic between Graylog and sigmaShooter, maybe the error is because there are no conexion between this machines...

Let me know if you could solve this problem.

When i can, i ll check the sigma conversion..

**Comment by s4lva2** [comment] 2020-08-07 14:41
Hi ppll0p1s 

No output is shown in the app terminal, neither in log file . It is only printed the error I mentioned earlier:

 Executed: runAllRules
[●] 2020/08/07 16:25:52.723283 http2: panic serving 192.168.1.145:50426: interface conversion: interface {} is nil, not float64
goroutine 521 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc000010330, 0xc0002e7f8e, 0xc000001e00)
	/usr/local/go/src/net/http/h2_bundle.go:5713 +0x16b
panic(0x844140, 0xc0001f3e30)
...

I checked tcpdump connectivity and it is ok in both directions:

14:33:27.485990 IP (tos 0x0, ttl 64, id 2796, offset 0, flags [DF], proto TCP (6), length 60)
    192.168.1.138.38400 > 192.168.1.140.9000: Flags [S], cksum 0x3d0b (correct), seq 883847272, win 29200, options [mss 1460,sackOK,TS val 63877744 ecr 0,nop,wscale 7], length 0
14:33:27.486066 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 60)
    192.168.1.140.9000 > 192.168.1.138.38400: Flags [S.], cksum 0x8495 (incorrect -> 0xed2d), seq 605067854, ack 883847273, win 65160, options [mss 1460,sackOK,TS val 1486990419 ecr 63877744,nop,wscale 7], length 0
....

Another diference I found is the graylog server version, I have Graylog v3.3.1+e2d4365 while in the manual that I was following the version is 3.2.4

Thanx in advance

**Comment by ppll0p1s** [comment] 2020-08-07 14:47
Please, verify that you are uncomment line 664 in $GOPATH/src/SigmaShooter/web/helpers.go.

**Comment by s4lva2** [comment] 2020-08-07 15:42
Hi,
I confirm that the line 664 is uncomment, but my installation is not in the path you tell, it is in /opt/SigmaShooter (I dont have defined $GOPATH env)

I have just install the graylog version 3.2.4 and it happens the same problem, but I have discovered if I shutdown the graylog server and then I run the sigma rules , I get the url in the log file

 2020/08/07 17:32:50.542287 runRuleQueryToGraylog: Get "http://192.168.1.140:9000/api/search/universal/relative?decorate=true&query=%28EventID%3A%221%22%20AND%20Image%3A%28%22%2Apowershell.exe%2A%22%29%20AND%20ParentImage%3A%28%22%2AWINWORD.EXE%2A%22%29%29%20AND%20NOT%20agentName%3ASigmaShooterAgent&range=86400": dial tcp 192.168.1.140:9000: i/o timeout
[●] 2020/08/07 17:32:50.544217 http2: panic serving 192.168.1.145:52708: runtime error: invalid memory address or nil pointer dereference

**Comment by s4lva2** [comment] 2020-08-07 15:49
This is the response, I think it is Ok

`{"query":"(EventID:\"1\" AND Image:(\"*powershell.exe*\") AND ParentImage:(\"*WINWORD.EXE*\")) AND NOT agentName:SigmaShooterAgent","built_query":"{\n  \"from\" : 0,\n  \"size\" : 150,\n  \"query\" : {\n    \"bool\" : {\n      \"must\" : [\n        {\n          \"query_string\" : {\n            \"query\" : \"(EventID:\\\"1\\\" AND Image:(\\\"*powershell.exe*\\\") AND ParentImage:(\\\"*WINWORD.EXE*\\\")) AND NOT agentName:SigmaShooterAgent\",\n            \"fields\" : [ ],\n            \"use_dis_max\" : true,\n            \"tie_breaker\" : 0.0,\n            \"default_operator\" : \"or\",\n            \"auto_generate_phrase_queries\" : false,\n            \"max_determinized_states\" : 10000,\n            \"allow_leading_wildcard\" : false,\n            \"enable_position_increments\" : true,\n            \"fuzziness\" : \"AUTO\",\n            \"fuzzy_prefix_length\" : 0,\n            \"fuzzy_max_expansions\" : 50,\n            \"phrase_slop\" : 0,\n            \"escape\" : false,\n            \"split_on_whitespace\" : true,\n            \"boost\" : 1.0\n          }\n        }\n      ],\n      \"filter\" : [\n        {\n          \"bool\" : {\n            \"must\" : [\n              {\n                \"range\" : {\n                  \"timestamp\" : {\n                    \"from\" : \"2020-08-06 15:44:35.406\",\n                    \"to\" : \"2020-08-07 15:44:35.406\",\n                    \"include_lower\" : true,\n                    \"include_upper\" : true,\n                    \"boost\" : 1.0\n                  }\n                }\n              }\n            ],\n            \"disable_coord\" : false,\n            \"adjust_pure_negative\" : true,\n            \"boost\" : 1.0\n          }\n        }\n      ],\n      \"disable_coord\" : false,\n      \"adjust_pure_negative\" : true,\n      \"boost\" : 1.0\n    }\n  },\n  \"sort\" : [\n    {\n      \"timestamp\" : {\n        \"order\" : \"desc\"\n      }\n    }\n  ]\n}","used_indices":[{"index_name":"graylog_1","begin":"1970-01-01T00:00:00.000Z","end":"1970-01-01T00:00:00.000Z","calculated_at":"2020-06-16T10:53:04.234Z","took_ms":0}],"messages":[],"fields":[],"time":104,"total_results":0,"from":"2020-08-06T15:44:35.406Z","to":"2020-08-07T15:44:35.406Z","decoration_stats":null}`

**Comment by ppll0p1s** [comment] 2020-08-07 16:00
Hi!
First, you have to recompile Sigmashooter with the uncomment 664 line if you want to apply the changes. If youw ant to modify the code and add or remove some code, you will have to recompile again.

Second, yes, the query seems OK, the error that Go is showing you indicates that the error is in web/apiController.go, line 488. In the response the field "total_results" doesn't exists, so it prints this error.
As we see in the response of graylog when you request the query manually, the field total_results exists... so this should not fail..
If fail.. is because the query from SigmaShooter server to Graylog is not playing well.

You could make some test from these server, for example, with curl, send that query to Graylog with the token configured? and check if the response is okey.

**Comment by s4lva2** [comment] 2020-08-07 16:26
I recompile the bin several times after the change but the result is the same. I recompiling using this:

`go build sigmaShooter.go`

I have checked with curl from the sigma server and the result is ok, I run this

`curl -v --user user:pass -X GET 'http://192.168.1.140:9000/api/search/universal/relative?decorate=true&query=(EventID%3A%221%22%20AND%20Image%3A(%22*powershell.exe*%22)%20AND%20ParentImage%3A(%22*WINWORD.EXE*%22))%20AND%20NOT%20agentName%3ASigmaShooterAgent&range=86400'
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 192.168.1.140...
* TCP_NODELAY set
* Connected to 192.168.1.140 (192.168.1.140) port 9000 (#0)
* Server auth using Basic with user 'user'
> GET /api/search/universal/relative?decorate=true&query=(EventID%3A%221%22%20AND%20Image%3A(%22*powershell.exe*%22)%20AND%20ParentImage%3A(%22*WINWORD.EXE*%22))%20AND%20NOT%20agentName%3ASigmaShooterAgent&range=86400 HTTP/1.1
> Host: 192.168.1.140:9000
> Authorization: Basic XXXYYYZZZ
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< X-Graylog-Node-ID: 6279b6d3-bfc3-4394-9340-90f47c91b816
< X-Runtime-Microseconds: 43859
< Content-Type: application/json
< Date: Fri, 07 Aug 2020 16:16:31 GMT
< Content-Length: 2262
< 
{"query":"(EventID:\"1\" AND Image:(\"*powershell.exe*\") AND ParentImage:(\"*WINWORD.EXE*\")) AND NOT agentName:SigmaShooterAgent","built_query":"{\n  \"from\" : 0,\n  \"size\" : 150,\n  \"query\" : {\n    \"bool\" : {\n      \"must\" : [\n        {\n          \"query_string\" : {\n            \"query\" : \"(EventID:\\\"1\\\" AND Image:(\\\"*powershell.exe*\\\") AND ParentImage:(\\\"*WINWORD.EXE*\\\")) AND NOT agentName:SigmaShooterAgent\",\n            \"fields\" : [ ],\n            \"use_dis_max\" : true,\n            \"tie_breaker\" : 0.0,\n            \"default_operator\" : \"or\",\n            \"auto_generate_phrase_queries\" : false,\n            \"max_determinized_states\" : 10000,\n            \"allow_leading_wildcard\" : false,\n            \"enable_position_increments\" : true,\n            \"fuzziness\" : \"AUTO\",\n            \"fuzzy_prefix_length\" : 0,\n            \"fuzzy_max_expansions\" : 50,\n            \"phrase_slop\" : 0,\n            \"escape\" : false,\n            \"split_on_whitespace\" : true,\n            \"boost\" : 1.0\n          }\n        }\n      ],\n      \"filter\" : [\n        {\n          \"bool\" : {\n            \"must\" : [\n              {\n                \"range\" : {\n                  \"timestamp\" : {\n                    \"from\" : \"2020-08-06 16:16:31.234\",\n                    \"to\" : \"2020-08-07 16:16:31.234\",\n                    \"include_lower\" : true,\n                    \"include_upper\" : true,\n                    \"boost\" : 1.0\n                  }\n                }\n              }\n            ],\n            \"disable_coord\" : false,\n            \"adjust_pure_negative\" : true,\n            \"boost\" : 1.0\n          }\n        }\n      ],\n      \"disable_coord\" : false,\n      \"adjust_pure_negative\" : true,\n      \"boost\" : 1.0\n    }\n  },\n  \"sort\" : [\n    {\n      \"timestamp\" : {\n        \"order\" : \"desc\"\n      }\n    }\n  ]\n}","used_indices":[{"index_name":"graylog_1","begin":"1970-01-01T00:00:00.000Z","end":"1970-01-01T0* Curl_http_done: called premature == 0
* Connection #0 to host 192.168.1.140 left intact
0:00:00.000Z","calculated_at":"2020-06-16T10:53:04.234Z","took_ms":0}],"messages":[],"fields":[],"time":4,"total_results":0,"from":"2020-08-06T16:16:31.234Z","to":"2020-08-07T16:16:31.234Z","decoration_stats":null}`

**Comment by ppll0p1s** [comment] 2020-08-07 16:30
Did u use the token configured in sigmashooter in the curl request?

**Comment by ppll0p1s** [comment] 2020-08-07 16:31
Capture tcpdump in the sigmashooter server with the option -X to see packets payloads and try to observe if you have the request and the correct answer, with the field total_results

**Comment by s4lva2** [comment] 2020-08-07 19:58
ppll0p1s ,

Tcpdump gave me the clue.
The problem was the user  that I use to create the token in graylog. This user has very few privileges so when sigmashooter tried to connect to graylog , it  was receiving a 403 error 
Adding this user to the admin group, the errors gone

Im sorry to open this kind of issue but I would like to say the errors in error log was confusing for me. 
If you release a new version in the future I think It would be a good idea to add this kind of errors in the error log

I would like to thank you for all the help you gave me
Thank you for your time

**Closed as completed** 2020-08-07 19:59 UTC
